# Conteúdo de cada página de projeto, lido por tools/gerar_projetos.py.
#
# Fontes: README e código de cada repositório e o array ROADMAP de
# roadmap.html. Ao mudar status, percentual ou próxima tarefa aqui, mude
# também no ROADMAP — os dois precisam dizer a mesma coisa.
#
# Campos principais de cada projeto:
#   status/percent  rótulo e % do ROADMAP (percent=None esconde a barra)
#   actions         botões do topo; DEMO para código privado, TALK para
#                   projeto em espera ou de uso pessoal
#   proof           faixa de números (só números conferidos no repositório)
#   done            o que já funciona
#   timeline ou built  segunda coluna: linha do tempo com datas reais de
#                   commits, ou "como está construído"
#   flow            4, 5 ou 6 passos de uso
#   why / vs        três diferenciais e a comparação com o jeito atual
#   next / spec     próximo passo do ROADMAP e ficha técnica
#   art             ilustração SVG (funções art_* no gerador)
DEMO = [{'label': 'Pedir uma demonstração', 'href': '#contato', 'primary': True}]
TALK = [{'label': 'Conversar sobre o projeto', 'href': '#contato', 'primary': True}]
PRIV = 'Código privado — demonstração sob pedido.'
NOTE_PRIV = 'Contado no repositório privado em 24 set 2026.'
PROJECTS = {}

PROJECTS['ebike-suporte'] = dict(
  name='EBike Suporte', short='EBike Suporte', sector='Bicicletarias', og='pós-venda de bike elétrica',
  desc='Pós-venda para lojas de bicicletas elétricas: ficha por bike, chamados com mensagens e equipe com papéis.',
  pitch='Pós-venda de bike elétrica <span class="grad">sem perder o histórico no WhatsApp.</span>',
  lede='Cada bicicleta tem ficha própria, e cada chamado fica registrado com mensagens, fotos e status — para a loja atender rápido e o cliente acompanhar.',
  status='MVP', chips=['Código privado', 'Web'], percent=70, actions=DEMO, hero_note=PRIV, art=art_ebike(),
  proof=[('57', 'casos de teste, com banco real'), ('3', 'migrações SQL versionadas'), ('3', 'papéis: cliente, funcionário e admin'), ('4', 'etapas de status do chamado')],
  proof_note=NOTE_PRIV,
  done=[('Ficha da bicicleta', ' com fotos e comprovante de compra'), ('Chamados com mensagens', ' entre cliente e loja'),
        ('Status do chamado', ': aberto, em andamento, aguardando cliente e resolvido'), ('Três papéis', ' com permissão linha a linha no banco'),
        ('Anexos', ' com controle de acesso'), ('Login com JWT', ' e rotas protegidas'), ('Sobe com um comando', ' via docker-compose')],
  built=[('Segurança no banco de dados', ' (Row Level Security): a regra vale mesmo fora do site'), ('Testes unitários e de integração', ' rodando contra PostgreSQL de verdade'),
         ('Migrações versionadas', ' e smoke test'), ('Next.js 16 e TypeScript', ' em modo estrito')],
  flow_eyebrow='Na loja', flow_title='Do cadastro da bike ao chamado resolvido',
  flow=[('Cadastra', 'O cliente cadastra a bike com fotos e comprovante.'), ('Abre', 'Descreve o problema num chamado.'), ('Atende', 'Um funcionário responde e troca mensagens.'),
        ('Acompanha', 'O admin atribui e define a prioridade.'), ('Resolve', 'O chamado fecha e o histórico fica na bike.')],
  why_title='Feito para a oficina de bike elétrica',
  why=[('shield', 'Segurança no próprio banco', 'A permissão vale no banco de dados, não só na tela: um cliente nunca vê o chamado de outro.'),
       ('history', 'Histórico por bicicleta', 'Garantia, revisões e defeitos ficam na ficha da bike, e não perdidos em conversas.'),
       ('users', 'Equipe com papéis', 'Cliente, funcionário e admin veem só o que precisam ver.')],
  vs=('Em vez de atender pelo WhatsApp pessoal da loja:', 'cada problema vira um chamado com dono, status e histórico.'),
  next=('Próximo passo', 'Validar com a primeira loja piloto', 'O sistema funciona; o próximo passo é colocá-lo numa loja real e ajustar com o uso. Pendências técnicas: recuperação de senha por e-mail e reabertura de chamado. 3 de 4 itens do roadmap concluídos.'),
  spec=[('Para quem é', 'Lojas e oficinas de bicicletas elétricas que precisam de histórico de atendimento por bike e controle de equipe.'),
        ('Como usar', 'Sistema web: a loja e o cliente usam pelo navegador, com o servidor e o banco PostgreSQL hospedados.'),
        ('Tecnologia', 'Next.js 16, TypeScript, PostgreSQL 17, Zod, Tailwind CSS 4 e Vitest.')],
  cta=('Tem uma loja de bikes elétricas?', 'Me chama no LinkedIn para ver o sistema funcionando com chamados de exemplo.'),
  pager=(('ai-control-center.html', 'AI Control Center'), ('autoatendimento-qr.html', 'Autoatendimento QR')))

PROJECTS['autoatendimento-qr'] = dict(
  name='Autoatendimento QR', short='Autoatendimento QR', sector='Restaurantes', og='pedido pela mesa',
  desc='Pedido por QR code, fila do garçom em tempo real e impressão na cozinha, funcionando na rede local sem internet.',
  pitch='O cliente pede pela mesa, <span class="grad">a cozinha imprime sozinha.</span>',
  lede='Pedido por QR code, fila do garçom em tempo real e cupom na impressora da cozinha — tudo na rede local, sem depender de internet.',
  status='MVP', chips=['Código privado', 'Windows + Android'], percent=75, actions=DEMO, hero_note=PRIV, art=art_qr(qr_svg(100, 97, 90)),
  proof=[('LAN', 'funciona na rede da loja, sem internet'), ('3', 'painéis: cliente, garçom e admin'), ('3', 'formas de pagar: dinheiro, cartão e Pix'), ('.exe + APK', 'instalador Windows e app Android')],
  proof_note='Conferido no código e no README do repositório privado em 24 set 2026.',
  done=[('Cardápio por QR code', ' com busca e categorias'), ('Comanda por pessoa', ' na mesma mesa'), ('Fila do garçom em tempo real', ', com sino'),
        ('Impressão térmica ESC/POS', ' com fila e nova tentativa'), ('Painel admin', ' com dashboard, cardápio e QR codes'), ('App Android assinado', ' para garçom e admin'),
        ('Login próprio', ' com proteção contra força bruta'), ('Apresentação comercial', ' pronta para mostrar ao cliente')],
  built=[('Servidor FastAPI + SQLite', ' rodando num PC da loja'), ('Instalador para Windows', ' (Inno Setup): não precisa instalar mais nada'),
         ('Pedido nunca duplica', ': a impressão é idempotente'), ('Tokens assinados (HMAC)', ' e limite de tentativas de login')],
  flow_eyebrow='No salão', flow_title='Da mesa até a cozinha, sem papel',
  flow=[('Escaneia', 'O cliente lê o QR code da mesa.'), ('Pede', 'Escolhe os itens no cardápio pelo celular.'), ('Avisa', 'O pedido cai na fila do garçom, com sino.'),
        ('Imprime', 'O garçom confirma e a cozinha recebe o cupom.'), ('Fecha', 'A conta fecha em dinheiro, cartão ou Pix.')],
  why_title='Feito para bar e lanchonete',
  why=[('wifi-off', 'Funciona sem internet', 'Tudo roda na rede local da loja. Se a internet cair, o salão continua pedindo.'),
       ('printer', 'Cozinha sem pedido perdido', 'O cupom sai na impressora térmica, sem duplicar e com nova tentativa se falhar.'),
       ('phone', 'Nada para o cliente instalar', 'O cardápio abre no navegador do celular, direto do QR code.')],
  vs=('Em vez de comanda de papel e garçom indo e voltando:', 'o pedido sai da mesa e chega na cozinha sozinho.'),
  next=('Próximo passo', 'Cobrança recorrente (Pix ou assinatura)', 'Para vender como serviço, faltam a assinatura mensal, o modo com várias lojas num só servidor e uma configuração inicial sem ajuda técnica. 4 de 7 itens do roadmap concluídos.'),
  spec=[('Para quem é', 'Bares, lanchonetes, food trucks e eventos pequenos com internet instável.'),
        ('Como instalar', 'Instalador para Windows no PC do caixa; o app Android e o cardápio no celular se conectam pela rede da loja.'),
        ('Tecnologia', 'FastAPI, SQLite, Socket.IO, PWA, PyInstaller e Inno Setup.')],
  cta=('Tem bar, lanchonete ou food truck?', 'Me chama no LinkedIn para ver o pedido saindo da mesa e chegando à cozinha.'),
  pager=(('ebike-suporte.html', 'EBike Suporte'), ('frota-lite.html', 'Frota Lite')))

PROJECTS['frota-lite'] = dict(
  name='Frota Lite', short='Frota Lite', sector='Frotas', og='manutenção de frota pequena',
  desc='Manutenção preventiva para frotas pequenas: quem está atrasado, próximo ou em dia, com a lista da oficina pronta para o WhatsApp.',
  pitch='Saiba qual veículo está <span class="grad">atrasado antes de quebrar.</span>',
  lede='Você informa o hodômetro; o sistema diz quem está atrasado, próximo ou em dia na revisão — e monta a lista da oficina para mandar pelo WhatsApp.',
  status='MVP', chips=['Código privado', 'Web'], percent=75, actions=DEMO, hero_note=PRIV, art=art_frota(),
  proof=[('45', 'casos de teste'), ('5', 'migrações SQL'), ('3', 'papéis: dono, gerente e membro'), ('12', 'commits desde 14 ago 2026')],
  proof_note=NOTE_PRIV,
  done=[('Painel', ' com atrasados, próximos e em dia, e custo por km'), ('Agenda da oficina', ' para WhatsApp, copiar ou imprimir'), ('Registro do hodômetro', ' quando o veículo volta'),
        ('Nota fiscal e foto', ' anexadas à manutenção'), ('Equipe', ' com convite por código e papéis'), ('Testes das regras de acesso', ' de cada papel'),
        ('Tema claro e escuro', ', e impressão sempre legível'), ('Frota de exemplo', ' para testar em um clique')],
  timeline=[('2026-08-14', '14 ago 2026', 'Primeira versão: painel, agenda da oficina e equipe.'), ('2026-09-06', '6 set', 'Reescrito em TanStack Start, com banco local para testar sem servidor.'),
            ('2026-09-19', '19 set', 'Novo visual com tema escuro e agenda pronta para imprimir.')],
  flow_eyebrow='No dia a dia', flow_title='Do hodômetro à oficina',
  flow=[('Roda', 'O veículo roda e volta para a base.'), ('Registra', 'O motorista ou gerente informa o hodômetro.'), ('Calcula', 'O sistema recalcula: atrasado, próximo ou em dia.'),
        ('Envia', 'O dono manda a agenda da oficina pelo WhatsApp.'), ('Guarda', 'A nota fiscal ou a foto fica anexada ao serviço.')],
  why_title='Simples para quem tem poucos veículos',
  why=[('gauge', 'Sem rastreador', 'Não precisa instalar nada no veículo: basta o número do hodômetro.'),
       ('send', 'Lista pronta para a oficina', 'A agenda sai formatada para WhatsApp, para copiar ou para imprimir.'),
       ('chart', 'Custo por km', 'O painel mostra quanto cada veículo custa para rodar.')],
  vs=('Em vez de controlar revisão num caderno:', 'o hodômetro entra e o sistema calcula sozinho o que está vencendo.'),
  next=('Próximo passo', 'Cobrança recorrente e passo a passo inicial', 'Faltam a assinatura mensal, um passo a passo para o dono configurar sozinho e o relatório de custo por km para exportar. 5 de 8 itens do roadmap concluídos.'),
  spec=[('Para quem é', 'Instaladoras, assistências técnicas e transportadoras pequenas que hoje controlam revisão no caderno.'),
        ('Como usar', 'Sistema web no computador ou no celular. Para testar, carregue a frota de exemplo.'),
        ('Tecnologia', 'React 19, TanStack Start, Tailwind v4, Better Auth e PostgreSQL (Neon) ou PGLite.')],
  cta=('Tem uma frota pequena?', 'Me chama no LinkedIn para ver a frota de exemplo funcionando.'),
  pager=(('autoatendimento-qr.html', 'Autoatendimento QR'), ('lumen.html', 'Lúmen')))

PROJECTS['lumen'] = dict(
  name='Lúmen', short='Lúmen', sector='Igrejas', og='projeção de culto que não trava',
  desc='Projeção de culto para Windows: letra, Bíblia, avisos e mídia no telão, operados por um voluntário, sem internet.',
  pitch='Projeção de culto que <span class="grad">não trava na frente da igreja.</span>',
  lede='Letra, Bíblia, avisos e mídia no telão, operados por um voluntário — sem internet e sem montar slide no PowerPoint a cada domingo.',
  status='Em teste', chips=['Código público', 'Windows'], percent=80,
  actions=[{'label': 'Baixar o instalador', 'href': 'https://github.com/orleans-samai/igreja-projetor/releases/latest', 'primary': True, 'icon': 'download', 'icon_first': True},
           {'label': 'Ver o código', 'href': 'https://github.com/orleans-samai/igreja-projetor', 'icon': 'arrow-up'}],
  art=art_lumen(),
  proof=[('32', 'versões publicadas no GitHub'), ('69', 'commits desde 6 set 2026'), ('59', 'arquivos de teste, rodados antes de cada versão'),
         ('33', 'temas prontos, 12 animados'), ('2', 'Bíblias completas offline')],
  proof_note='Contado no repositório público em 24 set 2026.',
  done=[('Instalador para Windows', ' que não pede senha de administrador'), ('Letras do Letras e do Vagalume', ', quebradas em slides sozinhas'),
        ('Bíblia inteira offline', ': Almeida 1819 e Bíblia Livre'), ('Celular como controle remoto', ', pareado lendo um QR code'),
        ('Pastor pede o versículo pelo celular', '; a cabine decide a hora'), ('Auto-Slide por voz', ', com o áudio processado no próprio PC'),
        ('Atualização automática', ': o app avisa quando sai versão nova'), ('Editor de artes e efeitos ao vivo', ' para montar o telão')],
  timeline=[('2026-09-06', '6 set 2026', 'Primeira versão: a cabine de projeção.'), ('2026-09-07', '7 set', 'Telão, instalador para Windows e biblioteca de mídia.'),
            ('2026-09-15', '15 set', 'Atualização automática: cada mudança aprovada vira uma versão publicada.'),
            ('2026-09-16', '16 set', 'O celular vira controle remoto, pareado por QR code.'), ('2026-09-20', '20 set', 'Editor de artes, efeitos ao vivo e assistente local.')],
  flow_eyebrow='No culto', flow_title='Como o voluntário usa, do começo ao fim',
  flow=[('Prepara', 'Busca as letras e monta a programação do culto.'), ('Confere', 'O check-up pré-culto testa telão, som e mídia.'),
        ('Projeta', 'F5 põe no ar, e as setas passam os slides.'), ('Acompanha', 'Os músicos veem cifra e o próximo slide no palco.'),
        ('Resolve', 'F9 põe um versículo de socorro no ar; se o app fechar, ele volta ao ponto exato.')],
  why_title='Feito para a cabine de igreja',
  why=[('wifi-off', 'Funciona sem internet', 'Bíblia, temas e letras salvas ficam no PC. A queda da rede não para o culto.'),
       ('moon', 'Pensado para o escuro', 'O que está no ar é sempre o mais claro da tela, e os controles nunca mudam de lugar.'),
       ('cpu', 'Roda em PC modesto', 'Os temas animados são desenhados em código, não em vídeo: instalador leve e pouco uso de processador.')],
  vs=('Em vez de montar slides no PowerPoint a cada culto:', 'a letra é buscada e quebrada em slides sozinha, a Bíblia inteira já está no app e o operador controla tudo pelo teclado ou pelo celular.'),
  next=('Próximo passo', 'Assinar o instalador', 'Hoje, na primeira instalação, o Windows avisa “editor desconhecido” porque o app ainda não tem certificado de assinatura. É o único item pendente do Lúmen no roadmap: 8 de 9 concluídos.'),
  spec=[('Para quem é', 'Igrejas pequenas e médias que projetam o culto num notebook ou PC com Windows.'),
        ('Como instalar', 'Baixe o <b>.exe</b> nas Releases do GitHub. Não precisa de Node.js nem de mais nada instalado antes.'),
        ('Tecnologia', 'Electron, React 19, TypeScript, TanStack Start e PGLite (banco local).')],
  cta=('Quer o Lúmen na cabine da sua igreja?', 'Me chama no LinkedIn e conversamos sobre como ele funciona no seu culto.'),
  pager=(('frota-lite.html', 'Frota Lite'), ('png-foto.html', 'Fundo Fora')))

PROJECTS['png-foto'] = dict(
  name='Fundo Fora', short='Fundo Fora', sector='Vendedores', og='remoção de fundo no celular',
  desc='Remova o fundo da foto do produto no próprio celular e exporte um PNG transparente, sem upload e sem marca d’água.',
  pitch='Fundo removido no celular, <span class="grad">sem a foto sair do aparelho.</span>',
  lede='Tire a foto do produto, remova o fundo e exporte um PNG transparente pronto para o anúncio — sem conta, sem marca d’água e sem upload.',
  status='Em desenvolvimento', chips=['Código privado', 'Android + Web'], percent=None, actions=DEMO, hero_note=PRIV, art=art_png(),
  proof=[('81', 'casos de teste'), ('~4,4 MB', 'modelo de IA, dentro do app'), ('0', 'fotos enviadas a servidor'), ('3/dia', 'recortes grátis, sem conta')],
  proof_note=NOTE_PRIV,
  done=[('Recorte no aparelho', ' de pessoa e de objeto'), ('PNG com transparência real', ' e borda suave'), ('Plano grátis e Pro', ': 3 recortes por dia ou ilimitado, até 4K'),
        ('Cobrança só depois', ' do primeiro recorte bem-sucedido'), ('Testes automáticos', ' da composição do PNG e do contador diário'), ('App Android nativo', ' pronto para gerar o pacote da Play Store')],
  built=[('Modelo U²-NetP', ' rodando com ONNX Runtime no próprio aparelho'), ('Módulo Android nativo', ' em Kotlin'), ('Testes no GitHub Actions', ' a cada push'), ('Primeira versão', ' em 5 set 2026')],
  flow_eyebrow='No celular', flow_title='Da foto ao anúncio',
  flow=[('Abre', 'Escolhe a foto do produto.'), ('Seleciona', 'Marca a pessoa ou o objeto que fica.'), ('Remove', 'O fundo sai no próprio aparelho.'),
        ('Ajusta', 'Suaviza a borda do recorte.'), ('Exporta', 'Salva o PNG transparente para o anúncio.')],
  why_title='Privado e pronto para vender',
  why=[('lock', 'A foto não sai do celular', 'Nada é enviado a servidor: o recorte acontece no aparelho.'),
       ('zap', 'Pronto para anunciar', 'PNG com transparência real, que funciona em qualquer marketplace.'),
       ('gift', 'Grátis para começar', 'Três recortes por dia, sem criar conta e sem marca d’água.')],
  vs=('Em vez de sites que pedem upload e colocam marca d’água:', 'o recorte acontece no aparelho e o arquivo é todo seu.'),
  next=('Próximo passo', 'Publicar na Play Store', 'O recorte já funciona; o que falta é publicar o app na Play Store e conquistar os primeiros usuários.'),
  spec=[('Para quem é', 'Vendedores de marketplace, artesãos, lojas de roupa e pequenos negócios que precisam de foto de produto para anúncio.'),
        ('Como usar', 'Versão web que roda no aparelho, e app Android pronto para a Play Store.'),
        ('Tecnologia', 'ONNX Runtime (WASM), modelo U²-NetP (Apache 2.0) e Kotlin.')],
  cta=('Vende pela internet?', 'Me chama no LinkedIn para ver o recorte funcionando com a foto de um produto seu.'),
  pager=(('lumen.html', 'Lúmen'), ('voice-finance.html', 'Voice Finance')))

PROJECTS['voice-finance'] = dict(
  name='Voice Finance', short='Voice Finance', sector='Finanças pessoais', og='gastos anotados por voz',
  desc='Registro de gastos por voz em português: o app entende valor, categoria e data. Projeto em espera.',
  pitch='Fale o gasto <span class="grad">e ele já está anotado.</span>',
  lede='“Gastei 45 no mercado hoje”: o app entende o valor, a categoria e a data e registra o lançamento — em português.',
  status='Em desenvolvimento', chips=['Código privado', 'Mobile', 'Em espera'], percent=None, actions=TALK, hero_note='Código privado. O projeto está em espera no roadmap.', art=art_voice(),
  proof=[('15', 'casos de teste do intérprete e das regras'), ('3', 'migrações com permissão por usuário'), ('LGPD', 'exportar e excluir os próprios dados')],
  proof_note=NOTE_PRIV,
  done=[('Registro por voz', ' com intérprete de linguagem natural'), ('Categorias e contas', ' configuráveis'), ('Exportação em JSON', ' e exclusão de conta (LGPD)'),
        ('Tela de privacidade', ' com as configurações do usuário'), ('Testes automáticos', ' do intérprete de voz')],
  built=[('React Native + Expo', ', com Expo Router'), ('Supabase', ' com Row Level Security: cada usuário só vê os próprios dados'), ('Revisão técnica aplicada', ' em 29 ago 2026')],
  flow_eyebrow='No dia a dia', flow_title='Da frase ao lançamento',
  flow=[('Fala', 'O usuário diz o gasto em linguagem natural.'), ('Entende', 'O app identifica valor, categoria e data.'), ('Confirma', 'O usuário confere ou edita antes de salvar.'),
        ('Organiza', 'O lançamento aparece nas categorias e contas.')],
  why_title='Anotar gasto sem formulário',
  why=[('mic', 'Em português do Brasil', 'O intérprete foi feito para frases do jeito que a gente fala.'),
       ('lock', 'Privacidade desde o banco', 'Cada usuário só acessa os próprios lançamentos, garantido no banco de dados.'),
       ('check', 'Você confirma antes', 'Nada é salvo sem você conferir o valor, a categoria e a data.')],
  vs=('Em vez de abrir o app e preencher um formulário a cada compra:', 'fala uma frase e confirma.'),
  next=('Situação', 'Projeto em espera', 'O Voice Finance não está entre as prioridades atuais do roadmap. A base — voz, banco e privacidade — funciona, mas não há data de lançamento.'),
  spec=[('Para quem é', 'Pessoas que pagam com Pix e cartão no dia a dia e esquecem de anotar os gastos.'),
        ('Como usar', 'App mobile com Expo; também roda no navegador para testes.'),
        ('Tecnologia', 'React Native, Expo, Supabase (Postgres com RLS) e Jest.')],
  cta=('Quer comando de voz no seu app?', 'Me chama no LinkedIn e conversamos sobre a ideia.'),
  pager=(('png-foto.html', 'Fundo Fora'), ('sistema-chamados.html', 'Sistema de Chamados')))

PROJECTS['sistema-chamados'] = dict(
  name='Sistema de Chamados', short='Sistema de Chamados', sector='Suporte de TI', og='service desk com laboratório',
  desc='Service desk com SLA, base de conhecimento, auditoria e laboratório de treinamento para analistas N1/N2. Código público.',
  pitch='Service desk completo, <span class="grad">com laboratório para treinar a equipe.</span>',
  lede='Abertura, atendimento e SLA de chamados, base de conhecimento e cenários simulados para analistas N1/N2 praticarem antes do atendimento real.',
  status='MVP', chips=['Código público', 'Web'], percent=85,
  actions=[{'label': 'Ver o código', 'href': 'https://github.com/orleans-samai/sistema-chamados', 'primary': True, 'icon': 'arrow-up'}, {'label': 'Fale comigo', 'href': '#contato'}],
  art=art_chamados(),
  proof=[('40', 'verificações automáticas no smoke test'), ('3', 'perfis de acesso'), ('Swagger', 'API REST documentada'), ('2', 'bancos: SQLite ou PostgreSQL')],
  proof_note='Conferido no repositório público em 24 set 2026.',
  done=[('Chamados numerados', ' com prioridade, status e SLA com alertas'), ('Painel', ' por status, categoria e analista'), ('Base de conhecimento', ' com busca'),
        ('Três perfis', ': admin, analista e usuário'), ('Auditoria', ' de todas as ações'), ('Exportação', ' em Excel e PDF'),
        ('API REST', ' documentada'), ('Laboratório N1/N2', ' com cenários simulados e gabarito')],
  built=[('Flask', ', com SQLite ou PostgreSQL'), ('Migrações', ' com Flask-Migrate e dados de exemplo'), ('Smoke test', ' cobrindo login, permissões, SLA, anexos e API'), ('Código aberto', ' no GitHub')],
  flow_eyebrow='No suporte', flow_title='Do chamado aberto ao relatório',
  flow=[('Abre', 'O usuário descreve o problema.'), ('Prioriza', 'O prazo de SLA começa a contar.'), ('Atende', 'O N1 resolve ou escala para o N2.'),
        ('Registra', 'Cada ação fica na auditoria.'), ('Mede', 'O chamado entra nos relatórios do painel.')],
  why_title='Operar e treinar no mesmo sistema',
  why=[('flask', 'Laboratório embutido', 'Analistas praticam cenários reais com gabarito antes de atender de verdade.'),
       ('clock', 'SLA à vista', 'O prazo de cada chamado aparece com alerta antes de estourar.'),
       ('eye', 'Tudo auditado', 'Quem fez o quê e quando fica registrado.')],
  vs=('Em vez de controlar chamados em planilha ou e-mail:', 'cada pedido tem número, prazo, responsável e histórico.'),
  next=('Próximo passo', 'Definir o uso comercial', 'O sistema está pronto e testado. Falta definir o foco comercial — como ferramenta de capacitação para escolas de TI e equipes de suporte. 2 de 3 itens do roadmap concluídos.'),
  spec=[('Para quem é', 'Equipes de suporte internas, escolas de TI e MSPs.'),
        ('Como usar', 'Sistema web em Python: roda num servidor da empresa ou localmente para treinamento.'),
        ('Tecnologia', 'Python, Flask, SQLite ou PostgreSQL, Bootstrap 5, Chart.js e Swagger.')],
  cta=('Precisa organizar o suporte ou treinar a equipe?', 'Me chama no LinkedIn ou veja o código aberto no GitHub.'),
  pager=(('voice-finance.html', 'Voice Finance'), ('ai-orchestrator.html', 'AI Orchestrator')))

PROJECTS['ai-orchestrator'] = dict(
  name='AI Orchestrator', short='AI Orchestrator', sector='Desenvolvedores', og='três IAs com aprovação humana',
  desc='Linha de comando que coordena três agentes de IA — planejar, implementar e revisar — com aprovação humana entre cada fase. Código público.',
  pitch='Três IAs no mesmo projeto, <span class="grad">e nada entra sem a sua aprovação.</span>',
  lede='Um agente planeja, outro implementa e um terceiro revisa. Entre cada fase, você decide — e nada é commitado sozinho.',
  status='MVP', chips=['Código público', 'Linux · linha de comando'], percent=None,
  actions=[{'label': 'Ver o código', 'href': 'https://github.com/orleans-samai/ai-orchestrator', 'primary': True, 'icon': 'arrow-up'},
           {'label': 'Manual em PDF', 'href': 'https://github.com/orleans-samai/ai-orchestrator/blob/main/docs/manual-pt-BR.pdf', 'icon': 'arrow-up'}],
  art=art_orch(),
  proof=[('3', 'agentes: Antigravity, Codex e Claude'), ('5', 'fases, cada uma com aprovação'), ('0', 'commits ou pushes automáticos')],
  proof_note='Conferido no repositório público em 24 set 2026.',
  done=[('Fluxo completo', ': planejar, implementar, revisar, validar e corrigir'), ('Aprovação humana', ' obrigatória em cada fase'), ('Relatório de cada execução', ' em .ai-runs/'),
        ('Escrita limitada', ' à pasta do projeto'), ('Revisor só lê', ': não edita arquivos'), ('Comando off', ' para parar sem perder o que foi gerado'), ('Manual em PDF', ' em português')],
  built=[('Um script em Bash', ' que conduz as CLIs agy, codex e claude'), ('Publicado', ' em 1 set 2026, com guia de uso e exemplo prático'), ('Licença, guia de contribuição', ' e política de segurança no repositório')],
  flow_eyebrow='No terminal', flow_title='Cada fase espera a sua decisão',
  flow=[('Planeja', 'O Antigravity monta o plano.'), ('Aprova', 'Você confere o plano.'), ('Implementa', 'O Codex escreve o código.'),
        ('Aprova', 'Você confere a implementação.'), ('Revisa', 'O Claude aponta os problemas.'), ('Decide', 'Você escolhe o que corrigir.')],
  why_title='Várias IAs, um responsável',
  why=[('hand', 'Você no controle', 'Nada avança, nem vira commit, sem a sua aprovação.'),
       ('layers', 'Um agente por vez', 'Os agentes não disputam os mesmos arquivos.'),
       ('file', 'Tudo rastreável', 'Cada execução gera um relatório com o que foi feito.')],
  vs=('Em vez de copiar e colar entre três ferramentas de IA:', 'um comando conduz o fluxo e para em cada decisão sua.'),
  next=('Próximo passo', 'Ainda não definido', 'O fluxo principal funciona e está documentado. O roadmap ainda não definiu a próxima etapa.'),
  spec=[('Para quem é', 'Desenvolvedores que usam vários agentes de programação no mesmo projeto e querem controle e rastreabilidade.'),
        ('Como usar', 'Script de linha de comando para Linux. Precisa das CLIs dos três agentes instaladas.'),
        ('Tecnologia', 'Bash e as CLIs agy, codex e claude.')],
  cta=('Usa vários agentes de IA no seu time?', 'Me chama no LinkedIn ou experimente pelo GitHub.'),
  pager=(('sistema-chamados.html', 'Sistema de Chamados'), ('excel-dashboard.html', 'Excel Dashboard')))

PROJECTS['excel-dashboard'] = dict(
  name='Excel Dashboard', short='Excel Dashboard', sector='Empresas', og='planilha vira painel, offline',
  desc='Transforma uma planilha Excel em painel com indicadores, gráficos e alertas, processado no próprio computador.',
  pitch='Sua planilha vira um painel <span class="grad">sem sair do seu computador.</span>',
  lede='Importe um Excel e receba indicadores, gráficos, tabela dinâmica e alertas de anomalias na hora — processado localmente, sem enviar dados para a nuvem.',
  status='MVP', chips=['Código privado', 'Desktop + Web'], percent=None, actions=DEMO, hero_note=PRIV, art=art_excel(),
  proof=[('3', 'formatos de exportação: PNG, PDF e Excel'), ('2', 'versões: web e desktop'), ('0', 'dados enviados para a nuvem')],
  proof_note='Conferido no código e no README do repositório privado em 24 set 2026.',
  done=[('Tipo de cada coluna', ' detectado sozinho: data, moeda, percentual ou categoria'), ('Indicadores e gráficos', ' sugeridos automaticamente'), ('Editor do painel', ' com layout salvo'),
        ('Tabela dinâmica', ' com totais'), ('Qualidade dos dados', ', com detecção de valores fora do padrão'), ('Colunas calculadas', ' por fórmula'),
        ('Tendência e previsão', ' ao longo do tempo'), ('Exportação', ' em PNG, PDF e Excel')],
  built=[('Next.js 14 e React 18', ' com TypeScript'), ('SheetJS', ' lê a planilha dentro do navegador'), ('Electron', ' para a versão desktop'), ('Primeira versão', ' em 5 ago 2026')],
  flow_eyebrow='Na prática', flow_title='Da planilha ao painel',
  flow=[('Importa', 'Abre a planilha .xlsx ou .xls.'), ('Reconhece', 'O tipo de cada coluna é detectado.'), ('Monta', 'Indicadores e gráficos aparecem na hora.'),
        ('Ajusta', 'Você edita o layout e cria colunas calculadas.'), ('Exporta', 'Salva em PNG, PDF ou Excel.')],
  why_title='Análise rápida e privada',
  why=[('lock', 'O dado não sai da máquina', 'Tudo é processado no seu computador, sem enviar a planilha para um serviço de fora.'),
       ('sparkles', 'Gráficos sugeridos', 'O painel se monta sozinho a partir das colunas da planilha.'),
       ('chart', 'Mais que gráficos', 'Tendência, previsão, correlação e alertas de anomalia.')],
  vs=('Em vez de montar gráfico por gráfico no Excel ou subir a planilha para um BI na nuvem:', 'importe e o painel se monta.'),
  next=('Próximo passo', 'Ainda não definido', 'O painel funciona na web e no desktop. O roadmap ainda não definiu a próxima etapa.'),
  spec=[('Para quem é', 'Analistas, consultores e o financeiro de pequenas e médias empresas que não podem enviar planilhas para a nuvem.'),
        ('Como usar', 'Abre no navegador ou como programa de desktop; a planilha é lida localmente.'),
        ('Tecnologia', 'Next.js 14, React 18, TypeScript, Tailwind CSS, Recharts, SheetJS e Electron.')],
  cta=('Tem planilhas que não podem ir para a nuvem?', 'Me chama no LinkedIn para ver o painel montado com dados de exemplo.'),
  pager=(('ai-orchestrator.html', 'AI Orchestrator'), ('central-da-festividade.html', 'Central da Festividade')))

PROJECTS['central-da-festividade'] = dict(
  name='Central da Festividade', short='Central da Festividade', sector='Igrejas', og='festividade num painel ao vivo',
  desc='Programação, escalas, avisos, visitantes e pedidos de oração da festividade num só lugar, com painel do dirigente ao vivo.',
  pitch='A festividade inteira <span class="grad">num painel ao vivo.</span>',
  lede='Programação, escalas, avisos, visitantes e pedidos de oração num só lugar — e o dirigente acompanha tudo em tempo real, do púlpito.',
  status='Em teste', chips=['Código privado', 'Web'], percent=65, actions=DEMO, hero_note=PRIV, art=art_fest(),
  proof=[('55', 'commits desde 23 ago 2026'), ('127', 'casos de teste'), ('11', 'migrações de banco'), ('CI', 'testes automáticos a cada push na main')],
  proof_note=NOTE_PRIV,
  done=[('Painel do dirigente', ' ao vivo'), ('Escalas', ' com confirmação por link, sem criar conta'), ('Voluntário avisa', ' quando não pode servir'),
        ('Recepção por PIN', ', separada do login normal'), ('Visitantes', ' com exportação CSV'), ('Pedidos de oração', ' e de intercessão'),
        ('Auditoria e backup', ' de todas as ações'), ('Painel pensado para o celular', ', com login sem e-mail')],
  timeline=[('2026-08-23', '23 ago 2026', 'Base: banco, sessão, admin e fluxo da recepção ao dirigente.'), ('2026-08-24', '24 ago', 'Escalas, avisos, intercessão, relatório em PDF e QR codes.'),
            ('2026-09-04', '4 set', 'Tempo real adaptado para publicar no plano gratuito da Vercel.'), ('2026-09-06', '5 e 6 set', 'Público de cada dia e aviso de indisponibilidade dos voluntários.'),
            ('2026-09-17', '16 e 17 set', 'Painel pensado para o celular e login sem e-mail.')],
  flow_eyebrow='No evento', flow_title='Da organização ao relatório final',
  flow=[('Organiza', 'Cria a festividade e define os PINs de acesso.'), ('Escala', 'Os voluntários confirmam por link, sem conta.'), ('Acompanha', 'O dirigente vê tudo ao vivo no painel.'),
        ('Recebe', 'A recepção cadastra visitantes e pedidos de oração.'), ('Fecha', 'Relatório e backup ficam prontos no final.')],
  why_title='Feito para eventos de igreja',
  why=[('users', 'Ninguém precisa criar conta', 'Voluntário confirma por link, e a recepção entra com PIN.'),
       ('eye', 'Ao vivo no púlpito', 'O dirigente acompanha programação, visitantes e pedidos em tempo real.'),
       ('shield', 'Tudo registrado', 'Auditoria das ações sensíveis e backup completo.')],
  vs=('Em vez de grupos de WhatsApp e planilhas de escala:', 'cada voluntário confirma pelo link e o dirigente vê tudo num painel.'),
  next=('Próximo passo', 'Facilitar a instalação para novas igrejas', 'Hoje, instalar exige configurar o banco PostgreSQL e o tempo real. O próximo passo é um roteiro de instalação para cada nova igreja. 6 de 7 itens do roadmap concluídos.'),
  spec=[('Para quem é', 'Igrejas que promovem festividades de vários dias, com voluntários escalados e recepção de visitantes.'),
        ('Como usar', 'Sistema web: organizadores, recepção e dirigente usam pelo navegador, inclusive no celular.'),
        ('Tecnologia', 'Next.js 16, React 19, TypeScript, Prisma 7, PostgreSQL, Vercel e Supabase.')],
  cta=('Sua igreja organiza festividades?', 'Me chama no LinkedIn para ver o painel do dirigente funcionando.'),
  pager=(('excel-dashboard.html', 'Excel Dashboard'), ('sliderevive-church-ai.html', 'SlideRevive Church AI')))

PROJECTS['sliderevive-church-ai'] = dict(
  name='SlideRevive Church AI', short='SlideRevive', sector='Igrejas', og='PDF da pregação vira slides',
  desc='Converte o PDF ou o PowerPoint da pregação em slides 16:9 para o telão, processado no navegador. Primeira versão.',
  pitch='O PDF da pregação <span class="grad">vira slides para o telão.</span>',
  lede='Importe o PDF ou o PowerPoint recebido e receba slides 16:9 prontos, com o tema escolhido pelo conteúdo — processado no navegador, sem enviar o arquivo.',
  status='MVP', chips=['Código privado', 'Web', 'Primeira versão'], percent=None, actions=DEMO, hero_note='Código privado — demonstração sob pedido. Primeira versão, ainda não testada com equipes de igreja.', art=art_slide(),
  proof=[('7', 'temas prontos'), ('25 MB', 'tamanho máximo do arquivo'), ('100', 'páginas ou slides por arquivo')],
  proof_note='Conferido no código e no README do repositório privado em 24 set 2026.',
  done=[('Importa PDF, PPTX e PPSX', ' até 25 MB'), ('Lê o texto localmente', ' e escolhe o tema pelo conteúdo'), ('Editor de slides', ' com duplicar e arrastar para reordenar'),
        ('Modo apresentação', ' em tela cheia'), ('Exporta de volta', ' para PowerPoint'), ('Botão para apagar', ' os dados salvos no aparelho')],
  built=[('Next.js e TypeScript', ', com Zustand e Framer Motion'), ('pdfjs-dist', ' lê o PDF dentro do navegador'), ('Primeira versão', ' em 29 ago 2026')],
  flow_eyebrow='Antes do culto', flow_title='Do arquivo recebido ao telão',
  flow=[('Importa', 'Abre o PDF ou o PowerPoint da pregação.'), ('Lê', 'O texto é extraído no próprio navegador.'), ('Monta', 'Os slides 16:9 saem com o tema escolhido.'),
        ('Revisa', 'A equipe reordena e ajusta.'), ('Usa', 'Apresenta direto ou exporta para PowerPoint.')],
  why_title='Preparar a projeção mais rápido',
  why=[('layers', 'Complementa o Lúmen', 'O SlideRevive prepara o material; o Lúmen projeta ao vivo.'),
       ('lock', 'O arquivo não sai do computador', 'Tudo é processado no navegador, sem upload.'),
       ('file', 'Volta para o PowerPoint', 'Exporta em .pptx ou .ppsx para quem usa outro programa.')],
  vs=('Em vez de copiar o texto da pregação slide por slide:', 'importe o arquivo e só revise.'),
  next=('Próximo passo', 'Ainda não definido', 'É uma primeira versão: funciona com PDF e apresentações com texto editável, ainda sem ler texto de imagens. O roadmap ainda não definiu a próxima etapa.'),
  spec=[('Para quem é', 'Equipes de mídia de igreja que recebem a pregação em PDF ou PowerPoint e precisam adaptar para o telão.'),
        ('Como usar', 'Abre no navegador; os arquivos ficam no próprio aparelho.'),
        ('Tecnologia', 'Next.js, React, TypeScript, Zustand, Framer Motion e pdfjs-dist.')],
  cta=('Sua equipe de mídia recebe a pregação em PDF?', 'Me chama no LinkedIn e conversamos sobre o projeto.'),
  pager=(('central-da-festividade.html', 'Central da Festividade'), ('netdiag-pro.html', 'NetDiag Pro')))

PROJECTS['netdiag-pro'] = dict(
  name='NetDiag Pro', short='NetDiag Pro', sector='Suporte de TI', og='diagnóstico de rede com relatório',
  desc='Diagnóstico de rede para suporte N1/N2: testa rede, DNS e portas, aponta a causa provável e gera o relatório em PDF.',
  pitch='Diagnóstico de rede em um clique, <span class="grad">relatório pronto para o chamado.</span>',
  lede='O técnico roda o app na máquina do cliente: ele testa rede, DNS e portas, aponta a causa provável e gera um PDF para anexar ao chamado.',
  status='MVP', chips=['Código privado', 'Windows'], percent=80, actions=DEMO, hero_note=PRIV, art=art_netdiag(),
  proof=[('v1.0.0', 'versão estável'), ('~50 MB', 'um único .exe'), ('~2 s', 'para abrir'), ('~80 MB', 'de memória em repouso')],
  proof_note='Números do README do repositório privado, conferidos em 24 set 2026.',
  done=[('Coleta automática', ' de hardware, rede, Wi-Fi e conexões ativas'), ('Testes', ' de ping, DNS, HTTPS, velocidade e portas'), ('Traceroute', ' e DNS reverso no modo completo'),
        ('Causa provável', ' com severidade e recomendação'), ('Relatório', ' em PDF e TXT'), ('Histórico', ' com comparação entre diagnósticos'), ('Modo usuário', ' e modo técnico')],
  built=[('Python', ' com interface CustomTkinter'), ('psutil e reportlab', ' para coleta e PDF'), ('Um único .exe', ' gerado com PyInstaller'), ('Regras legíveis', ': sem caixa-preta de IA')],
  flow_eyebrow='No atendimento', flow_title='Do clique ao relatório',
  flow=[('Executa', 'O técnico abre o app na máquina do cliente.'), ('Coleta', 'Hardware, rede e conexões ativas.'), ('Testa', 'Ping, DNS, portas e traceroute.'),
        ('Analisa', 'As regras apontam a causa provável.'), ('Relata', 'Gera o PDF para anexar ao chamado.')],
  why_title='Feito para o técnico de suporte',
  why=[('wifi-off', 'Offline e auditável', 'Cada regra de diagnóstico é código legível, adequado a empresas com política restrita.'),
       ('file', 'Relatório pronto', 'O PDF sai com os testes, a causa provável e a recomendação.'),
       ('monitor', 'Um .exe só', 'Não precisa instalar Python nem nada na máquina do cliente.')],
  vs=('Em vez de rodar ping, ipconfig e tracert na mão e copiar para o chamado:', 'um clique gera o relatório completo.'),
  next=('Próximo passo', 'Chave de licença', 'Para vender por licença a empresas de suporte, faltam a chave de licença, a assinatura do .exe e uma página com um PDF de exemplo. 3 de 6 itens do roadmap concluídos.'),
  spec=[('Para quem é', 'Equipes de suporte técnico N1/N2 e empresas que prestam suporte de TI (MSPs).'),
        ('Como usar', 'Um .exe para Windows, sem instalação. Roda na máquina que está com problema.'),
        ('Tecnologia', 'Python, CustomTkinter, psutil, reportlab e PyInstaller.')],
  cta=('Tem uma equipe de suporte ou MSP?', 'Me chama no LinkedIn para ver um relatório de exemplo.'),
  pager=(('sliderevive-church-ai.html', 'SlideRevive Church AI'), ('backend-python-simulator.html', 'Backend Python Simulator')))

PROJECTS['backend-python-simulator'] = dict(
  name='Backend Python Simulator', short='Backend Python Simulator', sector='Educação', og='aprender backend com tickets reais',
  desc='Simulador de carreira para backend em Python: 433 desafios corrigidos executando o código de verdade, 100% offline.',
  pitch='Aprender backend resolvendo <span class="grad">tickets de verdade.</span>',
  lede='O aluno trabalha como dev numa empresa fictícia: corrige bugs, escreve SQL e implementa APIs — e o sistema confere executando o código.',
  status='MVP', chips=['Código privado', 'Windows · Linux · macOS'], percent=55, actions=DEMO, hero_note=PRIV, art=art_bps(),
  proof=[('433', 'desafios'), ('8', 'níveis de carreira'), ('57', 'casos de teste do próprio sistema'), ('5', 'empresas temáticas')],
  proof_note='Conferido no código e no README do repositório privado em 24 set 2026.',
  done=[('433 desafios', ': tickets, bugs, logs, SQL, APIs, incidentes e code review'), ('Correção real', ': o código do aluno roda e é testado'), ('Mentor de IA local', ', que funciona offline'),
        ('XP, 8 níveis e certificados', ' em PDF'), ('Modo empresa', ': fintech, e-commerce, hospital, SaaS e marketplace'), ('Versão web', ' para vários alunos na mesma rede'),
        ('Instaladores', ' para Windows, Linux e macOS')],
  built=[('Desktop em PySide6 (Qt)', ', com SQLite e SQLAlchemy 2.0'), ('Corretor testado', ' com pytest'), ('Testes no GitHub Actions', ' a cada push na main'), ('Instalador Windows', ' com Inno Setup')],
  flow_eyebrow='Na trilha', flow_title='Do ticket ao certificado',
  flow=[('Recebe', 'Um ticket no estilo Jira.'), ('Resolve', 'Corrige o bug, escreve o SQL ou cria o endpoint.'), ('Confere', 'O sistema executa o código de verdade.'),
        ('Evolui', 'Ganha XP e sobe de nível.'), ('Certifica', 'Emite o certificado em PDF ao fim da trilha.')],
  why_title='Prática que parece trabalho de verdade',
  why=[('check', 'Correção de verdade', 'O código roda e o teste diz se passou, sem múltipla escolha.'),
       ('wifi-off', '100% offline', 'Sem Docker, sem servidor: instala e usa.'),
       ('award', 'Carreira gamificada', 'Do estagiário ao principal engineer, com certificados.')],
  vs=('Em vez de questionário de múltipla escolha:', 'o código do aluno roda, e o teste diz se passou.'),
  next=('Próximo passo', 'Painel para o professor', 'Para vender a escolas, faltam o painel da turma para acompanhar os alunos e mais trilhas de conteúdo. 2 de 4 itens do roadmap concluídos.'),
  spec=[('Para quem é', 'Estudantes de backend Python, escolas de TI, bootcamps e trilhas corporativas.'),
        ('Como instalar', 'Instaladores para Windows, Linux (AppImage e .deb) e macOS.'),
        ('Tecnologia', 'Python 3.10+, PySide6, SQLAlchemy 2.0, SQLite, FastAPI e reportlab.')],
  cta=('Ensina Python ou forma desenvolvedores?', 'Me chama no LinkedIn para ver um desafio sendo corrigido.'),
  pager=(('netdiag-pro.html', 'NetDiag Pro'), ('ai-control-center.html', 'AI Control Center')))

PROJECTS['ai-control-center'] = dict(
  name='AI Control Center', short='AI Control Center', sector='Desenvolvedores', og='seu uso de IA, organizado',
  desc='Lê as sessões do Claude Code e os repositórios Git da máquina e monta linha do tempo, custo estimado e ranking de projetos, 100% offline.',
  pitch='Seu uso de IA, <span class="grad">organizado sem sair do computador.</span>',
  lede='Lê as sessões do Claude Code e os repositórios Git da máquina e monta linha do tempo, resumo semanal, custo estimado e ranking de projetos — sem nenhuma requisição de rede.',
  status='Em desenvolvimento', chips=['Código privado', 'Desktop', 'Uso pessoal'], percent=None, actions=TALK, hero_note='Código privado. Feito para uso pessoal.', art=art_acc(),
  proof=[('180', 'casos de teste'), ('8', 'critérios no ranking de projetos'), ('0', 'requisições de rede')],
  proof_note=NOTE_PRIV,
  done=[('Linha do tempo', ' de sessões, commits e skills usadas'), ('Segredos removidos', ' antes de qualquer gravação'), ('Custo estimado', ' em tokens por sessão e por prompt'),
        ('Pendências de Git', ' com commit assistido'), ('Ranking de projetos', ' com 8 critérios'), ('Backup', ' em JSON e Markdown')],
  built=[('Electron 42 e React 19', ' com TypeScript'), ('Banco local', ' em SQLite (better-sqlite3)'), ('Testes dedicados', ' à remoção de segredos'), ('Primeira versão', ' em 23 ago 2026')],
  flow_eyebrow='No computador', flow_title='Dos arquivos locais ao ranking',
  flow=[('Lê', 'Sessões, skills e commits locais.'), ('Protege', 'Remove segredos antes de gravar.'), ('Resume', 'Linha do tempo, semana e custo.'),
        ('Compara', 'Cruza os repositórios no ranking.'), ('Guarda', 'Tudo fica num banco local, sem rede.')],
  why_title='Privado por padrão',
  why=[('wifi-off', 'Zero rede', 'Nenhuma requisição sai do computador: sem telemetria, sem analytics e sem atualização automática.'),
       ('shield', 'Segredos protegidos', 'Chaves e senhas são removidas antes de gravar.'),
       ('chart', 'Decisão com dados', 'O ranking mostra onde vale investir tempo.')],
  vs=('Em vez de lembrar de cabeça o que fez com a IA em cada projeto:', 'a linha do tempo mostra.'),
  next=('Situação', 'Uso pessoal, por enquanto', 'Feito para o meu próprio uso. Exportação em PDF e suporte a outros provedores de IA ainda não foram implementados.'),
  spec=[('Para quem é', 'Desenvolvedores que usam o Claude Code e querem entender o próprio uso e priorizar projetos.'),
        ('Como usar', 'Programa desktop que lê os arquivos locais do Claude Code e do Git.'),
        ('Tecnologia', 'Electron 42, React 19, TypeScript, Vite e better-sqlite3.')],
  cta=('Quer uma ferramenta assim para o seu time?', 'Me chama no LinkedIn e conversamos.'),
  pager=(('backend-python-simulator.html', 'Backend Python Simulator'), ('ebike-suporte.html', 'EBike Suporte')))
